functionsDirectory = "/Users/halperinio/Desktop/Ad Yaeli/Ad Yaeli and Back/netlify-deploy/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/halperinio/Desktop/Ad Yaeli/Ad Yaeli and Back/netlify-deploy"
publishOrigin = "config"
functions = "/Users/halperinio/Desktop/Ad Yaeli/Ad Yaeli and Back/netlify-deploy/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]